virtual_ship package
OceanParcels/Virtual_ship_classroom pull request #22
Opened 2024-04-15 12:22 UTC by surgura

- Packaged code in virtual_ship package
- Created pyproject.toml for project

It's just a first iteration, we will package and organize the code more thoroughly later.

@ammedd I left open the project description in the toml file for you to create.

2024-04-15 13:10 UTC, erikvansebille approved these changes
Good package structure, see a few suggestions and a question below

2024-04-15 13:10 UTC, erikvansebille commented on old_code.py
Why is this `old_code.py` file needed? Is it the old `virtualship.py`? Can't we just get it from the git history?

2024-04-15 13:10 UTC, erikvansebille commented on .gitignore
> +virtual_ship/_version_setup.py
Add a hard return at tend of file
```suggestion
virtual_ship/_version_setup.py

```

2024-04-15 13:10 UTC, erikvansebille commented on pyproject.toml
> +description = "Emma's work for the MSc student material. TODO Emma make a good description"
```suggestion
description = "Code for the Virtual Ship Classroom, where Marine Scientists can combine Copernicus Marine Data with an OceanParcels ship to go on a virtual expedition."
```

2024-04-15 13:10 UTC, erikvansebille commented on virtual_ship/costs.py
> +    '''Calculates cost of the virtual ship'''
```suggestion
    '''Calculates cost of the virtual ship (in US$)'''
```

2024-04-15 13:22 UTC, surgura commented on old_code.py
Need to discuss with Emma what code is relevant and what is not. Old code contains the code that is not used except by commented out lines. After this pr I will do a larger cleanup where we remove all that stuff. I just wanted to get the basics out there.

2024-04-15 14:10 UTC, surgura commented
Emma will first push the final code she still had locally on her computer. Then I will rearrange this pr.

2024-04-16 08:44 UTC, ammedd commented
Go ahead with the PR, I'll add things as issues

2024-04-16 11:02 UTC, ammedd requested changes

2024-04-16 11:02 UTC, ammedd commented on old_code.py
> +import json
Not old!

2024-04-16 12:34 UTC, ammedd approved these changes

2024-04-16 13:31 UTC, erikvansebille approved these changes

2024-04-16 14:14 UTC, merged